### ISSUE TITLE
Can't See Errors when Redirected for App TXs with Deposits 

### ISSUE THREAD

**Issue by mattlockyer** [near/near-wallet#1475] opened 2021-02-22 20:06 UTC
**Problem**
When app redirects to sign tx, if it fails the error is flashed on UI but redirect happens too fast.

**Expected Behavior**
User (or most likely dev) can see the error and read the message.

**Steps to reproduce**

1. Sign into app
2. Create tx with attached deposit (these redirect to wallet)
3. TX fails (maybe set it up to fail)

**Comment by corwinharrell** [comment] 2021-02-26 21:53
@marcinbodnar @Patrick1904 Curious to know why the error here is displayed on its own screen vs other errors in the app which use the toast pattern that displays briefly and then is automatically dismissed. Was this txn error implemented first?

**Comment by corwinharrell** [comment] 2021-03-01 17:09
@mattlockyer can you share a screen recording of this issue? I'm having trouble reproducing it just through the UI

**Comment by mattlockyer** [comment] 2021-03-01 19:51
![image](https://user-images.githubusercontent.com/321340/109550526-45305800-7a84-11eb-9723-349bad2369ca.png)

Click Buy

Redirected to Wallet

![image](https://user-images.githubusercontent.com/321340/109550572-54afa100-7a84-11eb-81bf-85c6ae4c43cb.png)

If there is an error with the TX, the error will flash up on the UI

BUT the user is redirected to app RIGHT AWAY. They do not get to read the error.

**Comment by corwinharrell** [comment] 2021-03-01 20:55
@mattlockyer haha yeah I understand the issue I was just hoping for a recording showing the error since I can't reproduce 😂

**Comment by corwinharrell** [comment] 2021-03-01 20:59
@mattlockyer haha yeah I get the issue I was just hoping for a video showing the issue itself since I cannot reproduce :)

**Comment by mattlockyer** [comment] 2021-03-01 22:55
A video isn't going to be any different.

I mean I can write a contract that fails all the time and show you. But it is exactly as I described.

Do you need an example that will fail that you can run on your machine?

**Comment by corwinharrell** [comment] 2021-03-02 01:25
@mattlockyer yeah I'd just like to see what we're working with so an easy way to reproduce would be ideal. Doesn't really matter how

**Comment by Patrick1904** [comment] 2021-03-02 02:07
@corwinharrell this is how a sign error currently looks. I encountered this timeout error (stayed on the page though) while buying a card on: https://berry.cards. It seems that the purchase still went through so we need to do better error handling of this in general and not just assume all of it failed.

![Screen Shot 2021-03-01 at 5 57 12 PM](https://user-images.githubusercontent.com/24921205/109585607-aa05a580-7ab8-11eb-8548-215d0a578112.png)

**Comment by marcinbodnar** [comment] 2021-03-02 19:22
@mattlockyer @Patrick1904  the problem here is with recent Mixpanel changes - at this moment, if `signAndSendTransactions` action fails, redirection is still executed - previously it was redirecting only on success. Checkout `handleAllow` in `Sign.js` component.

**Comment by corwinharrell** [comment] 2021-03-03 14:33
Removing the `Needs design` label here since design is present and it appears to just be an issue with timing and Mixpanel changes. @Patrick1904 I assume this can be addressed without the need for additional design given the context provided by @marcinbodnar above?

**Comment by Patrick1904** [comment] 2021-03-03 20:52
Thanks for investigating @marcinbodnar. I pushed a fix here: https://github.com/near/near-wallet/pull/1515

**Closed** 2021-03-03 21:02 UTC
Labels: 🛠 Needs Design

**Comment by marcinbodnar** [comment] 2021-03-03 22:45
> Thanks for investigating @marcinbodnar. I pushed a fix here: #1515

Great, thanks @Patrick1904
