### ISSUE TITLE
Enabling Ledger Hard Wallet should support selecting alternative HD path

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#2249] opened 2021-11-14 23:19 UTC
## Story

As a USER who wants to setup Ledger Hard Wallet, I want to select alternative HD path so I can have multiple not connected accounts on one Ledger device.

## Acceptance Criteria

- [ ] Multiple accounts managed with single Ledger but different public keys

## Assets

- Mockup: 

## NOTES

-

**Comment by MaximusHaximus** [comment] 2021-11-16 12:02
Thanks for the submission -- this is a duplicate of #2200 - this is on our radar (even is a ticket in our current sprint).  Merging this with #2200 (added Acceptance Criteria from this ticket to that one)

**Closed by MaximusHaximus** 2021-11-16 12:02 UTC
