### ISSUE TITLE
wallet.nearprotocol.com still has ability to create new accounts

### ISSUE THREAD

**Issue by mikedotexe** [near/near-wallet#810] opened 2020-08-12 22:52 UTC
A [user in Discord](https://discordapp.com/channels/490367152054992913/710764455398735906/743234220322717817) was confused today as he went to wallet.nearprotocol.com and created an account, which is the old testnet address. Then using create-near-app, it directed him to the proper testnet wallet site, and this caused him confusion.

Perhaps we can disable creating new accounts on the old domain?

<img width="896" alt="Screen Shot 2020-08-12 at 3 46 32 PM" src="https://user-images.githubusercontent.com/1042667/90076113-c3c5d380-dcb3-11ea-982c-e06e7eba163d.png">

**Comment by kcole16** [comment] 2020-08-12 22:55
Dupe of #733, but will fix ASAP!

**Closed by kcole16** 2020-08-12 22:55 UTC
