### ISSUE TITLE
Need a reliable SMS solution for districts including China and Vietnam

### ISSUE THREAD

**Issue by think-in-universe** [near/near-wallet#1989] opened 2021-07-31 07:26 UTC
**Problem**

The current twilio based SMS service is disabled for China and Vietnam users when registering a new account or 2FA, which makes the UX worse for the users. Considering we a large user base in China and Vietnam, the problem should be fixed. 

**Expected Behavior**

We have a reliable SMS solution that works for all the major districts including China and Vietnam. 

**Steps to reproduce**

1. Register a new account with +86 or +84 phone numbers;
2. No SMS can be received since CN/VN are disabeld:
  - CN: https://github.com/near/near-wallet/pull/1386
  - VN: https://github.com/near/near-wallet/pull/1939

**Comment by stefanopepe** [comment] 2021-08-02 13:03
Closing as it's a duplicate of #1950

**Closed by stefanopepe** 2021-08-02 13:03 UTC
Labels: Bug, Priority 2

**Comment by think-in-universe** [comment] 2021-08-03 07:08
@stefanopepe just want to confirm, what's the root cause of banning CN/VN at the moment?

**Comment by stefanopepe** [comment] 2021-08-13 17:01
Sorry I've lost the last reply. We don't have a clear reason but I suspect two main reasons:
1. the SMS is too long and is not accepted by the mobile operators
2. the message contains an URL from a blacklisted domain and is censored

We also had some "spam flag" coming from the SMS service (Twilio) but should be fixed now. Nevertheless, it doesn't work...
