### ISSUE TITLE
After transferring all 10 NEAR, there are still tokens left in the wallet

### ISSUE THREAD

**Issue by AnaisUrlichs** [near/near-wallet#449] opened 2020-03-16 13:58 UTC
## Story

As a USER I want to transfer all tokens from my wallet X to another wallet Y. (This situation will come up on mainnet). Even after transferring all the tokens, there is a small amount left. Without having any additional information, the user will likely be confused and think something went wrong.

Additionally, the "<" sign before the account funds might be interpreted as a "-" minus. 
![nearleft](https://user-images.githubusercontent.com/33576047/76765326-7f7ee780-6796-11ea-97fc-c75f6765133a.png)

**Comment by kcole16** [comment] 2020-03-17 19:46
@AnaisUrlichs This is by design, though we certainly could communicate it better to users

**Comment by kcole16** [comment] 2020-03-20 22:54
Watching result of https://github.com/nearprotocol/NEPs/issues/40

**Comment by ilblackdragon** [comment] 2020-03-21 10:20
If one wants to transfer ALL tokens, they must actually delete account and provide beneficiary the resulting account. Note, this is super dangerous as if you own anything else (NFT, some other token, etc) - you will loose it.

With nearprotocol/NEPs#40 we actually should make it more explicit that some amount of NEAR is required to be on the account to cover for storage.

**Comment by AnaisUrlichs** [comment] 2020-03-21 13:11
This will not be understood by the average user + seems to be quite dangerous in case someone accidentally transfers all their tokens.

**Comment by kcole16** [comment] 2020-05-28 23:32
Closing as users can no longer transfer all tokens (they must keep minimum balance)

**Closed by kcole16** 2020-05-28 23:32 UTC
Labels: Priority 3
