### ISSUE TITLE
near.org and nearprotocol.com create two different wallets

### ISSUE THREAD

**Issue by nearmax** [near/near-wallet#733] opened 2020-07-10 23:07 UTC
We support wallet both on near.org and on nearprotocol.com. Our website leads to nearprotocol.com and near-shell redirects to near.org. As the result accounts created on one domain cannot be used on another. Since we have both kinds of links it creates a pretty bad DevX

**Comment by vgrichina** [comment] 2020-07-11 05:51
This is not a bug on wallet side, local storage is scoped by domain. Accounts can be easily transferred through any of available recovery methods.

We need to fix link on website though.

@jakestutzman may you fix link on website to point to https://wallet.testnet.near.org?

**Comment by kcole16** [comment] 2020-07-13 17:15
Website is updated thanks to @jakestutzman. @vgrichina, at this point I'm thinking we just permanent redirect wallet.testnet.nearprotocol.com to near.org (etc for betanet and devnet). Thoughts?

**Closed** 2021-04-23 20:40 UTC
Labels: 🐞 Bug, 🧟‍♂️ Zombie!
