### ISSUE TITLE
If app is already authenticated doesn't redirect past the auth screen 

### ISSUE THREAD

**Issue by ckshei** [near/near-wallet#100] opened 2019-07-17 21:51 UTC
with an app that has already been authorized, you can still hit the 'Authenticate this app' page. 
Pressing allow will look broken, but will show this error message in the console: 

Error message: 
```
Error: Transaction CmiSWqLeoFATJoFVYA1iBKzaCe5yzDpTsSsTLVHjaAEv failed. Runtime error: Cannot add a public key that already exists on the account
    at p.signAndSendTransaction
```

**Comment by jimmy3dita** [comment] 2021-04-23 20:47
Duplicate of #960

**Closed by jimmy3dita** 2021-04-23 20:47 UTC
Labels: 🐞 Bug
