### ISSUE TITLE
Creating an account with ledger key doesn't allow to select key slot

### ISSUE THREAD

**Issue by nagisa** [near/near-wallet#2376] opened 2022-01-16 14:19 UTC
**Problem**

When recovering an account, the NEAR Wallet allows one to specify the HD path for the slot to use when recovering. However when creating an account one cannot do the same – the key at '1 HD path is used implicitly.

**Expected Behavior**

I don't know, perhaps there's value in making it possible to allow specifying which key at which HD path is to be used when creating a wallet?

**Steps to reproduce**

1. Go to https://wallet.testnet.near.org/setup-ledger/sometest.testnet.

**Comment by stefanopepe** [comment] 2022-01-19 09:00
This is a duplicate of #2200 .

**Closed by stefanopepe** 2022-01-19 09:00 UTC
